name: Size Label
on: pull_request_target

jobs:
  add_size_label:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@v3
      # install fetch so we can inject it
      # manually for Octokit
      - run: npm install node-fetch@2
        # install octokit so we can use it
        # in the next nodejs step
      - run: npm install @octokit/rest
        # install diff so we can use it
      - run: npm install diff
      - name: Add Size Label
        id: add_size_label
        uses: actions/github-script@v6
        env:
          CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          script: |
            const script = require('./.github/scripts/index.js')
            await script({context, core})
